### ISSUE TITLE
Can't determine track URL

### ISSUE THREAD

**Issue by pet0ruk** [Streamedian/html5_rtsp_player#34]
I can't play my RTSP stream at all, it always fails.  Here is the output from Firefox 51.0.1 (Windows 10 x64):

```
Specified "type" attribute of "application/x-rtsp" is not supported. Load of media resource rtsp://localhost:8011/live/peter failed.  index.html
All candidate resources failed to load. Media load paused.  index.html
Client paused  mybundle.js:36:30
Client started  mybundle.js:36:30
unreachable code after return statement[Learn More]  mybundle.js:1475:8
[mse] Media source opened: open  mybundle.js:36:30
[parser:sdp] v=0
o=- 39433591 39433591 IN IP4 127.0.0.1
s= 
c=IN IP4 127.0.0.1
t=0 0
a=sdplang:en
a=range:npt=0.0-
a=control:*
m=audio 0 RTP/AVP 96
a=rtpmap:96 mpeg4-generic/48000/2
a=fmtp:96 profile-level-id=1;mode=AAC-hbr;sizeLength=13;indexLength=3;indexDeltaLength=3;config=1190
a=control:trackID=1
m=video 0 RTP/AVP 97
a=rtpmap:97 H264/90000
a=fmtp:97 packetization-mode=1;profile-level-id=42C02A;sprop-parameter-sets=Z0LAKtoB4AiflhAAAAMAEAAAB4jxgyo=,aM48gA==
a=cliprect:0,0,1080,1920
a=framesize:97 1920-1080
a=framerate:60.0
a=control:trackID=2
  mybundle.js:36:30
[parser:sdp] Ignored unknown SDP directive: c=IN IP4 127.0.0.1  mybundle.js:36:30
[rtsp:stream] Can't determine track URL from block.control:trackID=1, session.control:*, and content-base:/live/peter/  mybundle.js:36:30
[rtsp:stream] Can't determine track URL from block.control:trackID=2, session.control:*, and content-base:/live/peter/  mybundle.js:36:30
[remuxer] Array [ Object, Object ]  mybundle.js:36:30
timescale: 16777216; unitsInTick: 48; fixedFramerate: false; avgFrameDuration: 174762.66666666666  mybundle.js:2128:17
Cannot play media. No decoders for requested formats: application/x-rtsp, application/x-rtsp  index.html
[rtsp:stream] Can't determine track URL from block.control:trackID=1, session.control:*, and content-base:/live/peter/  mybundle.js:36:30
[rtsp:stream] Can't determine track URL from block.control:trackID=2, session.control:*, and content-base:/live/peter/  mybundle.js:36:30
[client:rtsp] Not Found  mybundle.js:36:30
```

Here's the output from Chrome 56.0.2924.87 (Windows 10 x64):

```
mybundle.js:36 Client paused
mybundle.js:36 Client started
index.html:1 Error in event handler for (unknown): TypeError: Cannot read property 'state' of null
    at CSRecorder.onQueryStateCompleted (chrome-extension://cplklnmnlbnpmjogncfgfijoopmnlemp/content_scripts/recorder.js:106:17)
mybundle.js:36 [mse] Media source opened: open
mybundle.js:36 [parser:sdp] v=0
o=- 81932338 81932338 IN IP4 127.0.0.1
s= 
c=IN IP4 127.0.0.1
t=0 0
a=sdplang:en
a=range:npt=0.0-
a=control:*
m=audio 0 RTP/AVP 96
a=rtpmap:96 mpeg4-generic/48000/2
a=fmtp:96 profile-level-id=1;mode=AAC-hbr;sizeLength=13;indexLength=3;indexDeltaLength=3;config=1190
a=control:trackID=1
m=video 0 RTP/AVP 97
a=rtpmap:97 H264/90000
a=fmtp:97 packetization-mode=1;profile-level-id=42C02A;sprop-parameter-sets=Z0LAKtoB4AiflhAAAAMAEAAAB4jxgyo=,aM48gA==
a=cliprect:0,0,1080,1920
a=framesize:97 1920-1080
a=framerate:60.0
a=control:trackID=2

mybundle.js:36 [parser:sdp] Ignored unknown SDP directive: c=IN IP4 127.0.0.1
mybundle.js:36 [rtsp:stream] Can't determine track URL from block.control:trackID=1, session.control:*, and content-base:/live/peter/
_log @ mybundle.js:36
error @ mybundle.js:45
getSetupURL @ mybundle.js:2964
sendSetup @ mybundle.js:3013
start @ mybundle.js:2946
sendSetup @ mybundle.js:3676
mybundle.js:36 [rtsp:stream] Can't determine track URL from block.control:trackID=2, session.control:*, and content-base:/live/peter/
_log @ mybundle.js:36
error @ mybundle.js:45
getSetupURL @ mybundle.js:2964
sendSetup @ mybundle.js:3013
start @ mybundle.js:2946
sendSetup @ mybundle.js:3676
mybundle.js:36 [remuxer] [Object, Object]
mybundle.js:2128 timescale: 16777216; unitsInTick: 48; fixedFramerate: false; avgFrameDuration: 174762.66666666666
8mybundle.js:1746 broken chunk (continuation of lost frame)
mybundle.js:36 [rtsp:stream] Can't determine track URL from block.control:trackID=1, session.control:*, and content-base:/live/peter/
_log @ mybundle.js:36
error @ mybundle.js:45
getSetupURL @ mybundle.js:2964
sendKeepalive @ mybundle.js:2982
keepaliveInterval.setInterval @ mybundle.js:2993
mybundle.js:36 [rtsp:stream] Can't determine track URL from block.control:trackID=2, session.control:*, and content-base:/live/peter/
_log @ mybundle.js:36
error @ mybundle.js:45
getSetupURL @ mybundle.js:2964
sendKeepalive @ mybundle.js:2982
keepaliveInterval.setInterval @ mybundle.js:2993
mybundle.js:36 [client:rtsp] Not Found
```

Here's the proxy output from the server side on the Chrome load:

```
[2017-03-03 11:13:32] [connect] WebSocket Connection [::ffff:127.0.0.1]:39968 v13 "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36" /ws/ 101
xxxxxxxx-1 840553593: control connected
initializing rtsp connection
loading /var/www/html/wstest/libwsp_rtsp.so
loading libwsp_rtsp.so
create plugin
xxxxxxxx-1 840553593: connecting to localhost:8011
[2017-03-03 11:13:32] [connect] WebSocket Connection [::ffff:127.0.0.1]:39972 v13 "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36" /ws/ 101
xxxxxxxx-1 840553593: data connected
Stream resolution: 1920x1080
read headers: End of file
```

Here's an ffprobe of the stream (the link also plays fine in VLC):
```
{
Input #0, rtsp, from 'rtsp://localhost:8011/live/peter':
  Metadata:
    title           :
  Duration: N/A, start: -0.021667, bitrate: N/A
    Stream #0:0: Audio: aac (LC), 48000 Hz, stereo, fltp
    Stream #0:1: Video: h264 (Constrained Baseline), yuv420p(progressive), 1920x1080, 60 fps, 60 tbr, 90k tbn, 120 tbc
}
```

Even the Bunny test stream from Wowza doesn't play for me ( rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mov ).

Output in Chrome:

```
mybundle.js:36Client paused
mybundle.js:36Client started
mybundle.js:36 [mse] Media source opened: open
mybundle.js:36 [parser:sdp] v=0
o=- 1638481345 1638481345 IN IP4 54.204.234.134
s=BigBuckBunny_115k.mov
c=IN IP4 54.204.234.134
t=0 0
a=sdplang:en
a=range:npt=0- 596.48
a=control:*
m=audio 0 RTP/AVP 96
a=rtpmap:96 mpeg4-generic/12000/2
a=fmtp:96 profile-level-id=1;mode=AAC-hbr;sizelength=13;indexlength=3;indexdeltalength=3;config=1490
a=control:trackID=1
m=video 0 RTP/AVP 97
a=rtpmap:97 H264/90000
a=fmtp:97 packetization-mode=1;profile-level-id=42C01E;sprop-parameter-sets=Z0LAHtkDxWhAAAADAEAAAAwDxYuS,aMuMsg==
a=cliprect:0,0,160,240
a=framesize:97 240-160
a=framerate:24.0
a=control:trackID=2

mybundle.js:36 [parser:sdp] Ignored unknown SDP directive: c=IN IP4 54.204.234.134
mybundle.js:36 [remuxer] [Object, Object]0: Object1: Objectlength: 2__proto__: Array[0]
mybundle.js:2128 timescale: 16777216; unitsInTick: 12; fixedFramerate: false; avgFrameDuration: 699050.6666666666
2mybundle.js:36 [remuxer:base] Initial pts=0 dts=0
mybundle.js:36 [mse] Use codec: video/mp4; codecs="avc1.42c01e"
mybundle.js:36 [mse] Use codec: audio/mp4; codecs="mp4a.40.2"
```

It just hangs there and never plays.  Output from proxy:
```
[2017-03-03 11:21:13] [connect] WebSocket Connection [::ffff:127.0.0.1]:40026 v13 "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36" /ws/ 101
xxxxxxxx-1 214320222: control connected
initializing rtsp connection
loading /var/www/html/wstest/libwsp_rtsp.so
loading libwsp_rtsp.so
create plugin
xxxxxxxx-1 214320222: connecting to 184.72.239.149:554
[2017-03-03 11:21:13] [connect] WebSocket Connection [::ffff:127.0.0.1]:40030 v13 "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36" /ws/ 101
xxxxxxxx-1 214320222: data connected
Stream resolution: 240x160
```

And finally an ffprobe of the Wowza stream:
```
{
Input #0, rtsp, from 'rtsp://184.72.239.149/vod/mp4:BigBuckBunny_115k.mov':
  Metadata:
    title           : BigBuckBunny_115k.mov
  Duration: 00:09:56.48, start: 0.000000, bitrate: N/A
    Stream #0:0: Audio: aac (LC), 12000 Hz, stereo, fltp
    Stream #0:1: Video: h264 (Constrained Baseline), yuv420p(progressive), 240x160, 24 fps, 24 tbr, 90k tbn, 48 tbc
}
```

**Comment by kreopt** [comment]
There is some troubles in our player with BuckBunny audio track. We'll fix this case soon.
As for you stream, free version does not support FullHD video (You should be noticed about this in console but it seems this notification is broken now). Try to reduce video quality to 800*600 and tell us if it works

**Comment by pet0ruk** [comment]
Thanks for the information.  Here's the error output in Chrome with the stream at 800x600:
```
mybundle.js:36Client paused
mybundle.js:36Client started
index.html:1 Error in event handler for (unknown): TypeError: Cannot read property 'state' of null
    at CSRecorder.onQueryStateCompleted (chrome-extension://cplklnmnlbnpmjogncfgfijoopmnlemp/content_scripts/recorder.js:106:17)
mybundle.js:36 [mse] Media source opened: open
mybundle.js:36 [parser:sdp] v=0
o=- 81641565 81641565 IN IP4 127.0.0.1
s= 
c=IN IP4 127.0.0.1
t=0 0
a=sdplang:en
a=range:npt=0.0-
a=control:*
m=audio 0 RTP/AVP 96
a=rtpmap:96 mpeg4-generic/48000/2
a=fmtp:96 profile-level-id=1;mode=AAC-hbr;sizeLength=13;indexLength=3;indexDeltaLength=3;config=1190
a=control:trackID=1
m=video 0 RTP/AVP 97
a=rtpmap:97 H264/90000
a=fmtp:97 packetization-mode=1;profile-level-id=42C020;sprop-parameter-sets=Z0LAINoDIE35YQAAAwABAAADAHiPGDKg,aM48gA==
a=cliprect:0,0,600,800
a=framesize:97 800-600
a=framerate:60.0
a=control:trackID=2

mybundle.js:36 [parser:sdp] Ignored unknown SDP directive: c=IN IP4 127.0.0.1
mybundle.js:36 [rtsp:stream] Can't determine track URL from block.control:trackID=1, session.control:*, and content-base:/live/peter/
_log @ mybundle.js:36
error @ mybundle.js:45
getSetupURL @ mybundle.js:2964
sendSetup @ mybundle.js:3013
start @ mybundle.js:2946
sendSetup @ mybundle.js:3676
mybundle.js:36 [rtsp:stream] Can't determine track URL from block.control:trackID=2, session.control:*, and content-base:/live/peter/
_log @ mybundle.js:36
error @ mybundle.js:45
getSetupURL @ mybundle.js:2964
sendSetup @ mybundle.js:3013
start @ mybundle.js:2946
sendSetup @ mybundle.js:3676
mybundle.js:36 [remuxer] [Object, Object]
mybundle.js:2128 timescale: 16777219; unitsInTick: 768; fixedFramerate: false; avgFrameDuration: 10922.668619791666
10mybundle.js:1746 broken chunk (continuation of lost frame)
mybundle.js:36 [rtsp:stream] Can't determine track URL from block.control:trackID=1, session.control:*, and content-base:/live/peter/
_log @ mybundle.js:36
error @ mybundle.js:45
getSetupURL @ mybundle.js:2964
sendKeepalive @ mybundle.js:2982
keepaliveInterval.setInterval @ mybundle.js:2993
mybundle.js:36 [rtsp:stream] Can't determine track URL from block.control:trackID=2, session.control:*, and content-base:/live/peter/
_log @ mybundle.js:36
error @ mybundle.js:45
getSetupURL @ mybundle.js:2964
sendKeepalive @ mybundle.js:2982
keepaliveInterval.setInterval @ mybundle.js:2993
mybundle.js:36 [client:rtsp] Not Found
```

From the proxy:
```
[2017-03-06 11:00:58] [connect] WebSocket Connection [::ffff:127.0.0.1]:43548 v13 "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36" /ws/ 101
xxxxxx-1 1485732634: control connected
initializing rtsp connection
loading /home/peter/cah/libwsp_rtsp.so
loading libwsp_rtsp.so
create plugin
xxxxxx-1 1485732634: connecting to localhost:8011
[2017-03-06 11:00:58] [connect] WebSocket Connection [::ffff:127.0.0.1]:43552 v13 "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36" /ws/ 101
xxxxxx-1 1485732634: data connected
Stream resolution: 800x600
read headers: End of file
```

Firefox is pretty much the same as well.

**Comment by kreopt** [comment]
Hi! Could you test your 800x600 stream with latest player version? Buck Bunny stream is now works. And I see that your stream also using AAC-hbr which was unsupported.

**Comment by pet0ruk** [comment]
I'm having trouble building the new version, it doesn't like the async/await stuff:
`Error parsing /root/html5_rtsp_player/src/player.js: Unexpected token (159:10) in /root/html5_rtsp_player/src/player.js
Type rollup --help for help, or visit https://github.com/rollup/rollup/wiki`

**Comment by kreopt** [comment]
do you using rollup-buble plugin? you can disable it for testing in modern browsers if so.
or try to update rollup with npm. 
polyfills for async/await support in older browser will be added bit later

**Comment by pet0ruk** [comment]
I am not that familiar with node/npm I am just trying to follow the build instructions with a fresh directory, maybe I am doing something wrong.

I do this:
`git clone https://github.com/Streamedian/html5_rtsp_player.git
cd html5_rtsp_player
npm install
npm install bp_event bp_logger bp_statemachine
# edit example.js to change websocket URL
./node_modules/rollup/bin/rollup -c`

This worked for building previous module.  I updated rollup and the error is different:
`peter@stream:~/html5_rtsp_player$ npm install rollup@latest
streamedian@0.3.4 /home/peter/html5_rtsp_player
âââ rollup@0.41.6  invalid

npm WARN streamedian@0.3.4 license should be a valid SPDX license expression
peter@stream:~/html5_rtsp_player$ ./node_modules/rollup/bin/rollup -c
â ï¸   'default' is imported from external module 'rollup-plugin-buble' but never used

ð¨   Unexpected token
example.js (1:7)
1: gmport {LogLevel, getTagged, setDefaultLogLevel} from 'bp_logger';
          ^
2: import * as streamedian from 'streamedian/player.js';
3: import WebsocketTransport from 'streamedian/transport/websocket.js';`

npm version is 4.4.4 if it makes a difference

**Comment by pet0ruk** [comment]
Ok I think updating rollup fixed it:
```
peter@stream:~/html5_rtsp_player$ npm install rollup@latest
streamedian@0.3.4 /home/peter/html5_rtsp_player
âââ rollup@0.41.6  invalid

npm WARN streamedian@0.3.4 license should be a valid SPDX license expression
peter@stream:~/html5_rtsp_player$ ./node_modules/rollup/bin/rollup -c
â ï¸   'default' is imported from external module 'rollup-plugin-buble' but never used

peter@stream:~/html5_rtsp_player$ ls example/
index.html          streamedian.js      streamedian.js.map
```

I'll try to test now.

**Comment by pet0ruk** [comment]
I can confirm this fixes the issue with Big Buck Bunny but my own test stream still does not work (it is a live stream from OBS):
```
Client paused
Client started
[mse] Media source opened: open
streamedian.html:1 Error in event handler for (unknown): TypeError: Cannot read property 'state' of null
    at CSRecorder.onQueryStateCompleted (chrome-extension://cplklnmnlbnpmjogncfgfijoopmnlemp/content_scripts/recorder.js:106:17)
[mse] Media source ended: closed
[mse] Media source closed: closed
[mse] Media source opened: open
[parser:sdp] v=0
o=- 26998863 26998863 IN IP4 127.0.0.1
s= 
c=IN IP4 127.0.0.1
t=0 0
a=sdplang:en
a=range:npt=0.0-
a=control:*
m=audio 0 RTP/AVP 96
a=rtpmap:96 mpeg4-generic/44100/2
a=fmtp:96 profile-level-id=1;mode=AAC-hbr;sizeLength=13;indexLength=3;indexDeltaLength=3;config=1210
a=control:trackID=1
m=video 0 RTP/AVP 97
a=rtpmap:97 H264/90000
a=fmtp:97 packetization-mode=1;profile-level-id=4D401F;sprop-parameter-sets=Z01AH9oDIE35YQAAAwABAAADADyPGDKg,aO88gA==
a=cliprect:0,0,600,800
a=framesize:97 800-600
a=framerate:30.0
a=control:trackID=2

[parser:sdp] Ignored unknown SDP directive: c=IN IP4 127.0.0.1
[rtsp:stream] Can't determine track URL from block.control:trackID=1, session.control:*, and content-base:/live/peter/
_log @ streamedian.js:36
error @ streamedian.js:45
getSetupURL @ streamedian.js:2877
sendSetup @ streamedian.js:2926
start @ streamedian.js:2859
sendSetup @ streamedian.js:3851
[rtsp:stream] Can't determine track URL from block.control:trackID=2, session.control:*, and content-base:/live/peter/
_log @ streamedian.js:36
error @ streamedian.js:45
getSetupURL @ streamedian.js:2877
sendSetup @ streamedian.js:2926
start @ streamedian.js:2859
sendSetup @ streamedian.js:3851
[remuxer] [Object, Object]
timescale: 16777219; unitsInTick: 768; fixedFramerate: false; avgFrameDuration: 10922.668619791666
2 broken chunk (continuation of lost frame)
[rtsp:stream] Can't determine track URL from block.control:trackID=1, session.control:*, and content-base:/live/peter/
_log @ streamedian.js:36
error @ streamedian.js:45
getSetupURL @ streamedian.js:2877
sendKeepalive @ streamedian.js:2895
keepaliveInterval.setInterval @ streamedian.js:2906
[rtsp:stream] Can't determine track URL from block.control:trackID=2, session.control:*, and content-base:/live/peter/
_log @ streamedian.js:36
error @ streamedian.js:45
getSetupURL @ streamedian.js:2877
sendKeepalive @ streamedian.js:2895
keepaliveInterval.setInterval @ streamedian.js:2906
[client:rtsp] Not Found
```

If I change the resolution of my stream I see it change in the SDP information so the player definitely "sees" the stream through the WS proxy.

**Comment by kreopt** [comment]
please test your stream with latest @joastonish commit

**Comment by pet0ruk** [comment]
There's some progress here now!

I get audio which sounds fine and I get some very messed up video (green everywhere, flickering) but it's clearly progress.  The console is absolutely spammed with messages like this:
`[remuxer:h264] invalid AVC sample duration at PTS/DTS: 481500/481500|lastDTS: 481500:0`

After about 30 seconds the stream stops and in console it says:
`[client:rtsp] Not Found`

The proxy says:
read headers: End of file
```
[2017-04-21 15:43:11] [error] handle_read_frame error: websocketpp.transport:7 (End of File)
[2017-04-21 15:43:11] [disconnect] Disconnect close local:[1006,End of File] remote:[1006]
```

**Comment by kreopt** [comment]
do you have public url that I can test?

**Comment by Quynh-Nguyen** [comment]
I'm using Wowza Streaming and got same issue.
[remuxer:h264] invalid AVC sample duration at PTS/DTS: 1143090/1143090|lastDTS: 1149204:-6114  streamedian.js:36:30
[remuxer:h264] invalid AVC sample duration at PTS/DTS: 1149120/1149120|lastDTS: 1149204:-84  streamedian.js:36:30
[remuxer:h264] invalid AVC sample duration at PTS/DTS: 1275120/1275120|lastDTS: 1275234:-114  streamedian.js:36:30
[remuxer:h264] invalid AVC sample duration at PTS/DTS: 1476090/1476090|lastDTS: 1482168:-6078  streamedian.js:36:30
[remuxer:h264] invalid AVC sample duration at PTS/DTS: 1482120/1482120|lastDTS: 1482168:-48  streamedian.js:36:30
[remuxer:h264] invalid AVC sample duration at PTS/DTS: 1518120/1518120|lastDTS: 1518170:-50  streamedian.js:36:30
[remuxer:h264] invalid AVC sample duration at PTS/DTS: 1626120/1626120|lastDTS: 1626171:-51  streamedian.js:36:30
[remuxer:h264] invalid AVC sample duration at PTS/DTS: 1668060/1668060|lastDTS: 1674203:-6143  streamedian.js:36:30
[remuxer:h264] invalid AVC sample duration at PTS/DTS: 1674090/1674090|lastDTS: 1674203:-113  streamedian.js:36:30
[remuxer:h264] invalid AVC sample duration at PTS/DTS: 1722060/1722060|lastDTS: 1722202:-142

**Comment by kreopt** [comment]
Could you provide some public url with such stream to make me able to represent and fix this bug?

**Comment by Quynh-Nguyen** [comment]
Sorry I'm using localhost and Wowza Streaming server at:
rtsp://52.26.162.200:1935/live/3033
You can try in your side sir.

**Comment by pet0ruk** [comment]
The problem for me is that I am streaming to an RTMP server with OBS and then outputting to RTSP for this player, so I can't give a link as there would have to be someone streaming with OBS for it to work.  It should be quite easy to reproduce yourself though, I am using this to stream to https://github.com/iizukanao/node-rtsp-rtmp-server and it also provides the RTSP.

**Comment by kreopt** [comment]
@Quynh-Nguyen , could you enable you stream again to make me possible to complete fix? I have not much free time to setup wowza/obs streamer (first attempt was not successful) but if I'll have this stream for a couple of hours, i'll be able to debug it

**Comment by Quynh-Nguyen** [comment]
Are you online?

**Comment by kreopt** [comment]
Yes, I am

24 мая 2017 г. 17:32 пользователь "Quynh-Nguyen" <notifications@github.com>
написал:

**Comment by Quynh-Nguyen** [comment]
@kreopt rtsp://52.26.162.200:1935/live/3033 OR rtmp://52.26.162.200:1935/live/3033

**Comment by Quynh-Nguyen** [comment]
@kreopt It's okay?

**Comment by kreopt** [comment]
Done. @Quynh-Nguyen, @pet0ruk, please test

**Comment by pet0ruk** [comment]
@kreopt I am unable to test as I cannot build:
`Could not resolve '../../core/util/md5' from src/client/rtsp/client.js`

**Comment by kreopt** [comment]
fixed, please try again
