### ISSUE TITLE
Different problems on stopping and restart the player

### ISSUE THREAD

**Issue by mburger81** [Streamedian/html5_rtsp_player#54]
There are different problems on stopping and restarting the player doing this:
```
await this.wsPlayer.destroy();
this.wsPlayer = null;
this.wsPlayer = new WSPlayer(.....)
```
On doing this we have different problems, one of  exception we are running into is this:
```
console.js:26 Unhandled Promise rejection: Failed to execute 'remove' on 'SourceBuffer': This SourceBuffer is still processing an 'appendBuffer' or 'remove' operation. ; Zone: <root> ; Task: Promise.then ; Value: DOMException: Failed to execute 'remove' on 'SourceBuffer': This SourceBuffer is still processing an 'appendBuffer' or 'remove' operation.
    at promises.push.Promise (http://localhost:8100/build/0.js:34368:39)
    at new t (http://localhost:8100/build/polyfills.js:3:15044)
    at MSEBuffer.clear (http://localhost:8100/build/0.js:34366:31)
    at MSEBuffer.destroy (http://localhost:8100/build/0.js:34355:18)
    at MSE.reset (http://localhost:8100/build/0.js:34598:37)
    at MSE.destroy (http://localhost:8100/build/0.js:34527:18)
    at Remuxer.destroy (http://localhost:8100/build/0.js:35696:22)
    at WSPlayer.destroy (http://localhost:8100/build/0.js:38138:30)
    at <anonymous> Error: Failed to execute 'remove' on 'SourceBuffer': This SourceBuffer is still processing an 'appendBuffer' or 'remove' operation.
    at promises.push.Promise (http://localhost:8100/build/0.js:34368:39)
    at new t (http://localhost:8100/build/polyfills.js:3:15044)
    at MSEBuffer.clear (http://localhost:8100/build/0.js:34366:31)
    at MSEBuffer.destroy (http://localhost:8100/build/0.js:34355:18)
    at MSE.reset (http://localhost:8100/build/0.js:34598:37)
    at MSE.destroy (http://localhost:8100/build/0.js:34527:18)
    at Remuxer.destroy (http://localhost:8100/build/0.js:35696:22)
    at WSPlayer.destroy (http://localhost:8100/build/0.js:38138:30)
    at <anonymous>
console.(anonymous function) @ console.js:26
n.onUnhandledError @ polyfills.js:3
r @ polyfills.js:3
(anonymous) @ polyfills.js:3
n.microtaskDrainDone @ polyfills.js:3
o @ polyfills.js:3
Promise resolved (async)
r @ polyfills.js:3
c @ polyfills.js:3
t @ polyfills.js:3
clear @ rtsp_player.js:1004
destroy @ rtsp_player.js:993
reset @ rtsp_player.js:1236
destroy @ rtsp_player.js:1165
destroy @ rtsp_player.js:2334
destroy @ rtsp_player.js:4776
async function (async)
destroy @ rtsp_player.js:4765
(anonymous) @ la-rtsp-player.component.ts:97
step @ 0.js:33096
(anonymous) @ 0.js:33077
(anonymous) @ 0.js:33071
t @ polyfills.js:3
Array.concat.__awaiter @ 0.js:33067
Array.concat.LaRTSPlayerComponent.stopPlay @ la-rtsp-player.component.ts:95
(anonymous) @ la-rtsp-player.component.ts:122
step @ 0.js:33096
(anonymous) @ 0.js:33077
(anonymous) @ 0.js:33071
t @ polyfills.js:3
Array.concat.__awaiter @ 0.js:33067
Array.concat.LaRTSPlayerComponent.click @ la-rtsp-player.component.ts:118
(anonymous) @ LaRTSPlayerComponent.html:8
handleEvent @ core.es5.js:11914
callWithDebugContext @ core.es5.js:13206
debugHandleEvent @ core.es5.js:12794
dispatchEvent @ core.es5.js:8814
(anonymous) @ core.es5.js:9406
(anonymous) @ platform-browser.es5.js:2687
wrapped @ raven.js:321
t.invokeTask @ polyfills.js:3
onInvokeTask @ core.es5.js:4140
t.invokeTask @ polyfills.js:3
r.runTask @ polyfills.js:3
invoke @ polyfills.js:3
console.js:26 Error: Uncaught (in promise): InvalidStateError: Failed to execute 'remove' on 'SourceBuffer': This SourceBuffer is still processing an 'appendBuffer' or 'remove' operation.
Error: Failed to execute 'remove' on 'SourceBuffer': This SourceBuffer is still processing an 'appendBuffer' or 'remove' operation.
    at promises.push.Promise (rtsp_player.js:1006)
    at new t (polyfills.js:3)
    at MSEBuffer.clear (rtsp_player.js:1004)
    at MSEBuffer.destroy (rtsp_player.js:993)
    at MSE.reset (rtsp_player.js:1236)
    at MSE.destroy (rtsp_player.js:1165)
    at Remuxer.destroy (rtsp_player.js:2334)
    at WSPlayer.destroy (rtsp_player.js:4776)
    at <anonymous>
    at promises.push.Promise (rtsp_player.js:1006)
    at new t (polyfills.js:3)
    at MSEBuffer.clear (rtsp_player.js:1004)
    at MSEBuffer.destroy (rtsp_player.js:993)
    at MSE.reset (rtsp_player.js:1236)
    at MSE.destroy (rtsp_player.js:1165)
    at Remuxer.destroy (rtsp_player.js:2334)
    at WSPlayer.destroy (rtsp_player.js:4776)
    at <anonymous>
    at c (polyfills.js:3)
    at polyfills.js:3
    at t.invoke (polyfills.js:3)
    at r.run (polyfills.js:3)
    at polyfills.js:3
    at t.invokeTask (polyfills.js:3)
    at r.runTask (polyfills.js:3)
    at o (polyfills.js:3)
    at <anonymous>
```

**Comment by victorgrenke** [comment]
> On doing this we have different problems, 

Does this happen to any source or one of some kind?
