### ISSUE TITLE
 Failed to execute 'remove' on 'SourceBuffer'

### ISSUE THREAD

**Issue by mburger81** [Streamedian/html5_rtsp_player#60]
We use your lib on a mobile application, if the mobile application is go in PAUSE mode we destroy the player. When the app is resuming we create the player again, same thing as we do on fresh startup.
But in this case often we get this exception

```
vendor.js:138642 Unhandled Promise rejection: Failed to execute 'remove' on 'SourceBuffer': This SourceBuffer is still processing an 'appendBuffer' or 'remove' operation. ; Zone: <root> ; Task: Promise.then ; Value: DOMException: Failed to execute 'remove' on 'SourceBuffer': This SourceBuffer is still processing an 'appendBuffer' or 'remove' operation.
    at promises.push.Promise (file:///android_asset/www/build/0.js:34348:39)
    at new t (file:///android_asset/www/build/polyfills.js:3:15044)
    at MSEBuffer.clear (file:///android_asset/www/build/0.js:34346:31)
    at MSEBuffer.destroy (file:///android_asset/www/build/0.js:34335:18)
    at MSE.reset (file:///android_asset/www/build/0.js:34596:37)
    at MSE.destroy (file:///android_asset/www/build/0.js:34517:18)
    at Remuxer.destroy (file:///android_asset/www/build/0.js:35725:22)
    at WSPlayer.destroy (file:///android_asset/www/build/0.js:38208:30)
    at <anonymous> Error: Failed to execute 'remove' on 'SourceBuffer': This SourceBuffer is still processing an 'appendBuffer' or 'remove' operation.
    at promises.push.Promise (file:///android_asset/www/build/0.js:34348:39)
    at new t (file:///android_asset/www/build/polyfills.js:3:15044)
    at MSEBuffer.clear (file:///android_asset/www/build/0.js:34346:31)
    at MSEBuffer.destroy (file:///android_asset/www/build/0.js:34335:18)
    at MSE.reset (file:///android_asset/www/build/0.js:34596:37)
    at MSE.destroy (file:///android_asset/www/build/0.js:34517:18)
    at Remuxer.destroy (file:///android_asset/www/build/0.js:35725:22)
    at WSPlayer.destroy (file:///android_asset/www/build/0.js:38208:30)
    at <anonymous>
```

**Comment by mburger81** [comment]
We wasn't able to figure out which `appendBuffer` or `remove` is blocking the requested `remove` method but we do this in `MSEBuffer.clear()` method 
```
                    if (!this.sourceBuffer.updating) {
                        this.sourceBuffer.remove(this.sourceBuffer.buffered.start(i), this.sourceBuffer.buffered.end(i));
                        resolve();
                    } else {
                        this.sourceBuffer.onupdateend = () => {
                            this.sourceBuffer.remove(this.sourceBuffer.buffered.start(i), this.sourceBuffer.buffered.end(i));
                            resolve();
                        };
                    }
```
In our case this is resolving the issue, but as the lib is very complicated we are not sure if there could be some side effects in some cases

**Comment by mburger81** [comment]
created a PR #62
